{"uid":"ae45682a530d00d0","name":"存在しないサブコマンド","fullName":"features/record/common.feature#存在しないサブコマンド","historyId":"0dd3411c9cca6436e10d6331ddd3e37f:d41d8cd98f00b204e9800998ecf8427e","time":{"start":1734421056824,"stop":1734421056936,"duration":112},"description":"","status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"description":"","status":"passed","steps":[{"name":"When I run the command with args \"foo\"","time":{"start":1734421056824,"stop":1734421056935,"duration":111},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"Then I should get the exit code is non-zero","time":{"start":1734421056935,"stop":1734421056936,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"And The output error message should match with the pattern: \"Unknown argument: foo\"","time":{"start":1734421056936,"stop":1734421056936,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":3,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"host","value":"fv-az1215-533"},{"name":"language","value":"javascript"},{"name":"framework","value":"cucumberjs"},{"name":"thread","value":"2173"},{"name":"feature","value":"common"},{"name":"suite","value":"存在しないサブコマンド"},{"name":"tag","value":"@common"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["@common"]},"source":"ae45682a530d00d0.json","parameterValues":[]}